server:

  # 服务端口

  port: 8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account01?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name:
      com.mysql.cj.jdbc.Driver
  jwt:
      secret: AIAccountSystem2026JwtSecretKeyForLoginToken
      expire-time: 86400000

mybatis:

  # Mapper.xml路径

  mapper-locations:
    classpath:mapper/*.xml



  configuration:


    # 开启驼峰转换

    map-underscore-to-camel-case: true




logging:
  level:
    # 查看SQL
    com.demo.account.mapper: debug

ai:
  api-url: https://api.deepseek.com/chat/completions
  api-key: sk-c9cfb860fb4d429a94079b4085d486bf
  model: deepseek-chat




